/**
 * Created by Isitea on  7/24/2 17.
 */

    let GF_Guns = [
        { HH: 0, MM: 20, Type:  "HG", Rarity: 2, Character: { name: "M1911", SD: "" } },
        { HH: 0, MM: 20, Type:  "HG", Rarity: 2, Character: { name: "나강 리볼버", SD: "" } },
        { HH: 0, MM: 20, Type:  "HG", Rarity: 2, Character: { name: "P38", SD: "" } },
        { HH: 0, MM: 22, Type:  "HG", Rarity: 2, Character: { name: "PPK", SD: "" } },
        { HH: 0, MM: 25, Type:  "HG", Rarity: 2, Character: { name: "FNP-9", SD: "" } },
        { HH: 0, MM: 25, Type:  "HG", Rarity: 2, Character: { name: "MP-446", SD: "" } },
        { HH: 0, MM: 28, Type:  "HG", Rarity: 2, Character: { name: "USP Compact", SD: "" } },
        { HH: 0, MM: 28, Type:  "HG", Rarity: 2, Character: { name: "Bren Ten", SD: "" } },
        { HH: 0, MM: 30, Type:  "HG", Rarity: 3, Character: { name: "P 8", SD: "" } },
        { HH: 0, MM: 30, Type:  "HG", Rarity: 3, Character: { name: "C96", SD: "" } },
        { HH: 0, MM: 35, Type:  "HG", Rarity: 3, Character: { name: "92식", SD: "" } },
        { HH: 0, MM: 35, Type:  "HG", Rarity: 3, Character: { name: "P99", SD: "" } },
        { HH: 0, MM: 40, Type:  "HG", Rarity: 3, Character: { name: "아스트라 리볼버", SD: "" } },
        { HH: 0, MM: 40, Type:  "HG", Rarity: 3, Character: { name: "M9", SD: "" } },
        { HH: 0, MM: 40, Type:  "HG", Rarity: 3, Character: { name: "마카로프", SD: "" } },
        { HH: 0, MM: 45, Type:  "HG", Rarity: 3, Character: { name: "토카레프", SD: "" } },
        { HH: 0, MM: 50, Type:  "HG", Rarity: 4, Character: { name: "콜트 리볼버", SD: "" } },
        { HH: 0, MM: 50, Type:  "HG", Rarity: 4, Character: { name: "Mk23", SD: "" } },
        { HH: 0, MM: 52, Type:  "HG", Rarity: 4, Character: { name: "스핏파이어", SD: "" } },
        { HH: 0, MM: 55, Type:  "HG", Rarity: 4, Character: { name: "P7", SD: "" } },
        { HH: 0, MM: 55, Type:  "HG", Rarity: 4, Character: { name: "스테츠킨", SD: "" } },
        { HH: 1, MM:  0, Type:  "HG", Rarity: 5, Character: { name: "웰로드 MKII", SD: "" } },
        { HH: 1, MM:  5, Type:  "HG", Rarity: 5, Character: { name: "M950A", SD: "" } },
        { HH: 1, MM:  6, Type: "SMG", Rarity: 2, Character: { name: "M3", SD: "" } },
        { HH: 1, MM: 10, Type:  "HG", Rarity: 5, Character: { name: "그리즐리 MkV", SD: "" } },
        { HH: 1, MM: 10, Type: "SMG", Rarity: 2, Character: { name: "IDW", SD: "" } },
        { HH: 1, MM: 10, Type: "SMG", Rarity: 2, Character: { name: "PP-2 0", SD: "" } },
        { HH: 1, MM: 20, Type: "SMG", Rarity: 2, Character: { name: "Spectre M4", SD: "" } },
        { HH: 1, MM: 20, Type: "SMG", Rarity: 2, Character: { name: "M45", SD: "" } },
        { HH: 1, MM: 25, Type: "SMG", Rarity: 2, Character: { name: "64식", SD: "" } },
        { HH: 1, MM: 30, Type: "SMG", Rarity: 2, Character: { name: "MP40", SD: "" } },
        { HH: 1, MM: 30, Type: "SMG", Rarity: 2, Character: { name: "베레타 38형", SD: "" } },
        { HH: 1, MM: 30, Type: "SMG", Rarity: 2, Character: { name: "M3", SD: "" } },
        { HH: 1, MM: 40, Type: "SMG", Rarity: 3, Character: { name: "스텐 Mk.II", SD: "" } },
        { HH: 1, MM: 40, Type: "SMG", Rarity: 3, Character: { name: "마이크로 우지", SD: "" } },
        { HH: 1, MM: 50, Type: "SMG", Rarity: 2, Character: { name: "PPSh-41", SD: "" } },
        { HH: 2, MM:  0, Type: "SMG", Rarity: 3, Character: { name: "MAC-10", SD: "" } },
        { HH: 2, MM:  0, Type: "SMG", Rarity: 3, Character: { name: "스콜피온", SD: "" } },
        { HH: 2, MM: 10, Type: "SMG", Rarity: 3, Character: { name: "PPS-43", SD: "" } },
        { HH: 2, MM: 15, Type: "SMG", Rarity: 4, Character: { name: "UMP9", SD: "" } },
        { HH: 2, MM: 15, Type: "SMG", Rarity: 4, Character: { name: "UMP45", SD: "" } },
        { HH: 2, MM: 18, Type: "SMG", Rarity: 4, Character: { name: "시프카", SD: "" } },
        { HH: 2, MM: 20, Type: "SMG", Rarity: 4, Character: { name: "MP5", SD: "" } },
        { HH: 2, MM: 20, Type: "SMG", Rarity: 4, Character: { name: "PP-90", SD: "" } },
        { HH: 2, MM: 25, Type: "SMG", Rarity: 5, Character: { name: "수오미", SD: "" } },
        { HH: 2, MM: 30, Type: "SMG", Rarity: 5, Character: { name: "톰슨", SD: "" } },
        { HH: 2, MM: 30, Type: "SMG", Rarity: 5, Character: { name: "G36C", SD: "" } },
        { HH: 2, MM: 33, Type: "SMG", Rarity: 5, Character: { name: "SR-3MP", SD: "" } },
        { HH: 2, MM: 35, Type: "SMG", Rarity: 5, Character: { name: "벡터", SD: "" } },
        { HH: 2, MM: 35, Type: "SMG", Rarity: 5, Character: { name: "79식", SD: "" } },
        { HH: 2, MM: 40, Type:  "AR", Rarity: 2, Character: { name: "갈릴", SD: "" } },
        { HH: 2, MM: 40, Type:  "AR", Rarity: 2, Character: { name: "SIG-510", SD: "" } },
        { HH: 2, MM: 45, Type:  "AR", Rarity: 2, Character: { name: "F2 0", SD: "" } },
        { HH: 2, MM: 45, Type:  "AR", Rarity: 2, Character: { name: "63식", SD: "" } },
        { HH: 2, MM: 50, Type:  "AR", Rarity: 2, Character: { name: "L85A1", SD: "" } },
        { HH: 2, MM: 50, Type:  "AR", Rarity: 2, Character: { name: "G3", SD: "" } },
        { HH: 3, MM:  0, Type:  "AR", Rarity: 3, Character: { name: "StG44", SD: "" } },
        { HH: 3, MM: 10, Type:  "AR", Rarity: 3, Character: { name: "OTs-12", SD: "" } },
        { HH: 3, MM: 10, Type:  "RF", Rarity: 2, Character: { name: "G43", SD: "" } },
        { HH: 3, MM: 10, Type:  "RF", Rarity: 2, Character: { name: "FN-49", SD: "" } },
        { HH: 3, MM: 20, Type:  "AR", Rarity: 3, Character: { name: "AK-47", SD: "" } },
        { HH: 3, MM: 20, Type:  "AR", Rarity: 3, Character: { name: "FNC", SD: "" } },
        { HH: 3, MM: 20, Type:  "RF", Rarity: 2, Character: { name: "BM59", SD: "" } },
        { HH: 3, MM: 25, Type:  "AR", Rarity: 4, Character: { name: "56-1식", SD: "" } },
        { HH: 3, MM: 30, Type:  "AR", Rarity: 4, Character: { name: "AS Val", SD: "" } },
        { HH: 3, MM: 30, Type:  "AR", Rarity: 4, Character: { name: "FAMAS", SD: "" } },
        { HH: 3, MM: 30, Type:  "AR", Rarity: 4, Character: { name: "TAR-21", SD: "" } },
        { HH: 3, MM: 30, Type:  "RF", Rarity: 2, Character: { name: "시모노프", SD: "" } },
        { HH: 3, MM: 30, Type:  "RF", Rarity: 2, Character: { name: "SVT-38", SD: "" } },
        { HH: 3, MM: 35, Type:  "AR", Rarity: 4, Character: { name: "9A-91", SD: "" } },
        { HH: 3, MM: 40, Type:  "AR", Rarity: 4, Character: { name: "G36", SD: "" } },
        { HH: 3, MM: 40, Type:  "AR", Rarity: 4, Character: { name: "리베롤", SD: "" } },
        { HH: 3, MM: 40, Type:  "RF", Rarity: 3, Character: { name: "M14", SD: "" } },
        { HH: 3, MM: 40, Type:  "RF", Rarity: 3, Character: { name: "SV-98", SD: "" } },
        { HH: 3, MM: 45, Type:  "AR", Rarity: 5, Character: { name: "FAL", SD: "" } },
        { HH: 3, MM: 50, Type:  "AR", Rarity: 5, Character: { name: "95식", SD: "" } },
        { HH: 3, MM: 50, Type:  "AR", Rarity: 5, Character: { name: "97식", SD: "" } },
        { HH: 3, MM: 50, Type:  "RF", Rarity: 3, Character: { name: "한양조88식", SD: "" } },
        { HH: 3, MM: 55, Type:  "AR", Rarity: 5, Character: { name: "HK416", SD: "" } },
        { HH: 3, MM: 58, Type:  "AR", Rarity: 5, Character: { name: "RFB", SD: "" } },
        { HH: 4, MM:  0, Type:  "RF", Rarity: 3, Character: { name: "M1 개런드", SD: "" } },
        { HH: 4, MM:  4, Type:  "AR", Rarity: 5, Character: { name: "G11", SD: "" } },
        { HH: 4, MM:  5, Type:  "AR", Rarity: 5, Character: { name: "G41", SD: "" } },
        { HH: 4, MM: 10, Type:  "RF", Rarity: 4, Character: { name: "모신나강", SD: "" } },
        { HH: 4, MM: 15, Type:  "RF", Rarity: 4, Character: { name: "SVD", SD: "" } },
        { HH: 4, MM: 25, Type:  "RF", Rarity: 4, Character: { name: "스프링필드", SD: "" } },
        { HH: 4, MM: 30, Type:  "RF", Rarity: 4, Character: { name: "PTRD", SD: "" } },
        { HH: 4, MM: 40, Type:  "RF", Rarity: 5, Character: { name: "Kar98k", SD: "" } },
        { HH: 4, MM: 45, Type:  "RF", Rarity: 5, Character: { name: "NTW-20", SD: "" } },
        { HH: 4, MM: 50, Type:  "RF", Rarity: 5, Character: { name: "WA2 0", SD: "" } },
        { HH: 4, MM: 50, Type:  "MG", Rarity: 2, Character: { name: "AAT-52", SD: "" } },
        { HH: 4, MM: 50, Type:  "MG", Rarity: 2, Character: { name: "FG42", SD: "" } },
        { HH: 4, MM: 52, Type:  "RF", Rarity: 5, Character: { name: "IWS 2 0", SD: "" } },
        { HH: 4, MM: 55, Type:  "RF", Rarity: 5, Character: { name: "M99", SD: "" } },
        { HH: 5, MM:  0, Type:  "RF", Rarity: 5, Character: { name: "리엔필드", SD: "" } },
        { HH: 5, MM:  0, Type:  "MG", Rarity: 2, Character: { name: "MG34", SD: "" } },
        { HH: 5, MM:  0, Type:  "MG", Rarity: 2, Character: { name: "DP28", SD: "" } },
        { HH: 5, MM: 10, Type:  "MG", Rarity: 2, Character: { name: "LWMMG", SD: "" } },
        { HH: 5, MM: 20, Type:  "MG", Rarity: 3, Character: { name: "브렌", SD: "" } },
        { HH: 5, MM: 40, Type:  "HG", Rarity: 3, Character: { name: "M1919A4", SD: "" } },
        { HH: 5, MM: 50, Type:  "HG", Rarity: 3, Character: { name: "MG42", SD: "" } },
        { HH: 6, MM: 10, Type:  "MG", Rarity: 4, Character: { name: "M60", SD: "" } },
        { HH: 6, MM: 10, Type:  "MG", Rarity: 3, Character: { name: "M2HB", SD: "" } },
        { HH: 6, MM: 20, Type:  "MG", Rarity: 4, Character: { name: "Mk48", SD: "" } },
        { HH: 6, MM: 20, Type:  "MG", Rarity: 4, Character: { name: "AEK-999", SD: "" } },
        { HH: 6, MM: 25, Type:  "MG", Rarity: 4, Character: { name: "M1918", SD: "" } },
        { HH: 6, MM: 30, Type:  "MG", Rarity: 4, Character: { name: "PK", SD: "" } },
        { HH: 6, MM: 30, Type:  "MG", Rarity: 4, Character: { name: "MG3", SD: "" } },
        { HH: 6, MM: 35, Type:  "MG", Rarity: 5, Character: { name: "네게브", SD: "" } },
        { HH: 6, MM: 40, Type:  "MG", Rarity: 5, Character: { name: "MG4", SD: "" } },
        { HH: 6, MM: 45, Type:  "MG", Rarity: 5, Character: { name: "MG5", SD: "" } },
        { HH: 6, MM: 50, Type:  "MG", Rarity: 5, Character: { name: "PKP", SD: "" } },
        { HH: 7, MM: 20, Type:  "SG", Rarity: 3, Character: { name: "M50", SD: "" } },
        { HH: 7, MM: 25, Type:  "SG", Rarity: 3, Character: { name: "KS-23", SD: "" } },
        { HH: 7, MM: 30, Type:  "SG", Rarity: 3, Character: { name: "RMB-93", SD: "" } },
        { HH: 7, MM: 30, Type:  "SG", Rarity: 3, Character: { name: "M1897", SD: "" } },
        { HH: 7, MM: 40, Type:  "SG", Rarity: 4, Character: { name: "M590", SD: "" } },
        { HH: 7, MM: 40, Type:  "SG", Rarity: 4, Character: { name: "SPAS-12", SD: "" } },
        { HH: 7, MM: 45, Type:  "SG", Rarity: 4, Character: { name: "M37", SD: "" } },
        { HH: 7, MM: 50, Type:  "SG", Rarity: 4, Character: { name: "Super Shorty", SD: "" } },
        { HH: 8, MM:  0, Type:  "SG", Rarity: 5, Character: { name: "KSG", SD: "" } }
    ];