/**
 * Created by Isitea on 07/24/2017.
 */

    let gun = [
        { HH: "0", MM: "20", Rarity: "★★", Type: "HG", List: [ "M1911", "나강 리볼버", "P38" ] },
        { HH: "0", MM: "22", Rarity: "★★", Type: "HG", List: [ "PPK" ] },
        { HH: "0", MM: "25", Rarity: "★★", Type: "HG", List: [ "FNP-9", "MP-446" ] },
        { HH: "0", MM: "28", Rarity: "★★", Type: "HG", List: [ "USP Compact", "Bren Ten" ] },
        { HH: "0", MM: "30", Rarity: "★★★", Type: "HG", List: [ "P08", "C96" ] },
        { HH: "0", MM: "35", Rarity: "★★★", Type: "HG", List: [ "92식", "P99" ] },
        { HH: "0", MM: "40", Rarity: "★★★", Type: "HG", List: [ "아스트라 리볼버", "M9", "마카로프" ] },
        { HH: "0", MM: "45", Rarity: "★★★", Type: "HG", List: [ "토카레프" ] },
        { HH: "0", MM: "50", Rarity: "★★★★", Type: "HG", List: [ "콜트 리볼버", "Mk23" ] },
        { HH: "0", MM: "52", Rarity: "★★★★", Type: "HG", List: [ "스핏파이어" ] },
        { HH: "0", MM: "55", Rarity: "★★★★", Type: "HG", List: [ "P7", "스테츠킨" ] },
        { HH: "1", MM: "00", Rarity: "★★★★★", Type: "HG", List: [ "웰로드 MKII" ] },
        { HH: "1", MM: "05", Rarity: "★★★★★", Type: "HG", List: [ "M950A" ] },
        { HH: "1", MM: "06", Rarity: "★★", Type: "SMG", List: [ "M3" ] },
        { HH: "1", MM: "10", Rarity: "★★★★★", Type: "HG", List: [ "그리즐리 MkV" ] },
        { HH: "1", MM: "10", Rarity: "★★", Type: "SMG", List: [ "IDW", "PP-2000" ] },
        { HH: "1", MM: "20", Rarity: "★★", Type: "SMG", List: [ "Spectre M4", "M45" ] },
        { HH: "1", MM: "25", Rarity: "★★", Type: "SMG", List: [ "64식" ] },
        { HH: "1", MM: "30", Rarity: "★★", Type: "SMG", List: [ "MP40", "베레타 38형", "M3" ] },
        { HH: "1", MM: "40", Rarity: "★★★", Type: "SMG", List: [ "스텐 Mk.II", "마이크로 우지" ] },
        { HH: "1", MM: "50", Rarity: "★★", Type: "SMG", List: [ "PPSh-41" ] },
        { HH: "2", MM: "00", Rarity: "★★★", Type: "SMG", List: [ "MAC-10", "스콜피온" ] },
        { HH: "2", MM: "10", Rarity: "★★★", Type: "SMG", List: [ "PPS-43" ] },
        { HH: "2", MM: "15", Rarity: "★★★★", Type: "SMG", List: [ "UMP9", "UMP45" ] },
        { HH: "2", MM: "18", Rarity: "★★★★", Type: "SMG", List: [ "시프카" ] },
        { HH: "2", MM: "20", Rarity: "★★★★", Type: "SMG", List: [ "MP5", "PP-90" ] },
        { HH: "2", MM: "25", Rarity: "★★★★★", Type: "SMG", List: [ "수오미" ] },
        { HH: "2", MM: "30", Rarity: "★★★★★", Type: "SMG", List: [ "톰슨", "G36C" ] },
        { HH: "2", MM: "33", Rarity: "★★★★★", Type: "SMG", List: [ "SR-3MP" ] },
        { HH: "2", MM: "35", Rarity: "★★★★★", Type: "SMG", List: [ "벡터", "79식" ] },
        { HH: "2", MM: "40", Rarity: "★★", Type: "AR", List: [ "갈릴", "SIG-510" ] },
        { HH: "2", MM: "45", Rarity: "★★", Type: "AR", List: [ "F2000", "63식" ] },
        { HH: "2", MM: "50", Rarity: "★★", Type: "AR", List: [ "L85A1", "G3" ] },
        { HH: "3", MM: "00", Rarity: "★★★", Type: "AR", List: [ "StG44" ] },
        { HH: "3", MM: "10", Rarity: "★★★", Type: "AR", List: [ "OTs-12" ] },
        { HH: "3", MM: "10", Rarity: "★★", Type: "RF", List: [ "G43", "FN-49" ] },
        { HH: "3", MM: "20", Rarity: "★★★", Type: "AR", List: [ "AK-47", "FNC" ] },
        { HH: "3", MM: "20", Rarity: "★★", Type: "RF", List: [ "BM59" ] },
        { HH: "3", MM: "25", Rarity: "★★★★", Type: "AR", List: [ "56-1식" ] },
        { HH: "3", MM: "30", Rarity: "★★★★", Type: "AR", List: [ "AS Val", "FAMAS", "TAR-21" ] },
        { HH: "3", MM: "30", Rarity: "★★", Type: "RF", List: [ "시모노프", "SVT-38" ] },
        { HH: "3", MM: "35", Rarity: "★★★★", Type: "AR", List: [ "9A-91" ] },
        { HH: "3", MM: "40", Rarity: "★★★★", Type: "AR", List: [ "G36", "리베롤" ] },
        { HH: "3", MM: "40", Rarity: "★★★", Type: "RF", List: [ "M14", "SV-98" ] },
        { HH: "3", MM: "45", Rarity: "★★★★★", Type: "AR", List: [ "FAL" ] },
        { HH: "3", MM: "50", Rarity: "★★★★★", Type: "AR", List: [ "95식", "97식" ] },
        { HH: "3", MM: "50", Rarity: "★★★", Type: "RF", List: [ "한양조88식" ] },
        { HH: "3", MM: "55", Rarity: "★★★★★", Type: "AR", List: [ "HK416" ] },
        { HH: "3", MM: "58", Rarity: "★★★★★", Type: "AR", List: [ "RFB" ] },
        { HH: "4", MM: "00", Rarity: "★★★", Type: "RF", List: [ "M1 개런드" ] },
        { HH: "4", MM: "04", Rarity: "★★★★★", Type: "AR", List: [ "G11" ] },
        { HH: "4", MM: "05", Rarity: "★★★★★", Type: "AR", List: [ "G41" ] },
        { HH: "4", MM: "10", Rarity: "★★★★", Type: "RF", List: [ "모신나강" ] },
        { HH: "4", MM: "15", Rarity: "★★★★", Type: "RF", List: [ "SVD" ] },
        { HH: "4", MM: "25", Rarity: "★★★★", Type: "RF", List: [ "스프링필드" ] },
        { HH: "4", MM: "30", Rarity: "★★★★", Type: "RF", List: [ "PTRD" ] },
        { HH: "4", MM: "40", Rarity: "★★★★★", Type: "RF", List: [ "Kar98k" ] },
        { HH: "4", MM: "45", Rarity: "★★★★★", Type: "RF", List: [ "NTW-20" ] },
        { HH: "4", MM: "50", Rarity: "★★★★★", Type: "RF", List: [ "WA2000" ] },
        { HH: "4", MM: "50", Rarity: "★★", Type: "MG", List: [ "AAT-52", "FG42" ] },
        { HH: "4", MM: "52", Rarity: "★★★★★", Type: "RF", List: [ "IWS 2000" ] },
        { HH: "4", MM: "55", Rarity: "★★★★★", Type: "RF", List: [ "M99" ] },
        { HH: "5", MM: "00", Rarity: "★★★★★", Type: "RF", List: [ "리엔필드" ] },
        { HH: "5", MM: "00", Rarity: "★★", Type: "MG", List: [ "MG34", "DP28" ] },
        { HH: "5", MM: "10", Rarity: "★★", Type: "MG", List: [ "LWMMG" ] },
        { HH: "5", MM: "20", Rarity: "★★★", Type: "MG", List: [ "브렌" ] },
        { HH: "5", MM: "40", Rarity: "★★★", Type: "HG", List: [ "M1919A4" ] },
        { HH: "5", MM: "50", Rarity: "★★★", Type: "HG", List: [ "MG42" ] },
        { HH: "6", MM: "10", Rarity: "★★★★", Type: "MG", List: [ "M60" ] },
        { HH: "6", MM: "10", Rarity: "★★★", Type: "MG", List: [ "M2HB" ] },
        { HH: "6", MM: "20", Rarity: "★★★★", Type: "MG", List: [ "Mk48", "AEK-999" ] },
        { HH: "6", MM: "25", Rarity: "★★★★", Type: "MG", List: [ "M1918" ] },
        { HH: "6", MM: "30", Rarity: "★★★★", Type: "MG", List: [ "PK", "MG3" ] },
        { HH: "6", MM: "35", Rarity: "★★★★★", Type: "MG", List: [ "네게브" ] },
        { HH: "6", MM: "40", Rarity: "★★★★★", Type: "MG", List: [ "MG4" ] },
        { HH: "6", MM: "45", Rarity: "★★★★★", Type: "MG", List: [ "MG5" ] },
        { HH: "6", MM: "50", Rarity: "★★★★★", Type: "MG", List: [ "PKP" ] },
        { HH: "7", MM: "20", Rarity: "★★★", Type: "SG", List: [ "M500" ] },
        { HH: "7", MM: "25", Rarity: "★★★", Type: "SG", List: [ "KS-23" ] },
        { HH: "7", MM: "30", Rarity: "★★★", Type: "SG", List: [ "RMB-93", "M1897" ] },
        { HH: "7", MM: "40", Rarity: "★★★★", Type: "SG", List: [ "M590", "SPAS-12" ] },
        { HH: "7", MM: "45", Rarity: "★★★★", Type: "SG", List: [ "M37" ] },
        { HH: "7", MM: "50", Rarity: "★★★★", Type: "SG", List: [ "Super Shorty" ] },
        { HH: "8", MM: "00", Rarity: "★★★★★", Type: "SG", List: [ "KSG" ] }
    ];

    let out = [];
    for ( let i of gun ) {
        for ( let k of i.List ) {
            out.push( {
                HH: i.HH,
                MM: i.MM,
                Type: i.Type,
                Rarity: i.Rarity.length,
                Character: {
                    name: k,
                    SD: ""
                }
            } );
        }
    }
    console.log( JSON.stringify( out ) );